spec/openapi.yaml, web/swagger-docs/changelog.md
* `amount_including_tax` is being added to OrderDetail output
* `currency` is added to Order output
=> Version 1.1.23 updates

web/swagger-docs/changelog.md
=> Add 1.1.25 updates to changelog

spec/openapi.yaml, web/swagger-docs/changelog.md
=> Update OrderArticle specification for purchase price addition

spec/openapi.yaml, web/swagger-docs/changelog.md
=> Document order payment status changes

spec/openapi.yaml, web/swagger-docs/changelog.md
Also added extra information on payment flow and possible statuses
=> CASH-929 - Zero amount orders 

spec/openapi.yaml
Note: changelog will be adjusted once orders can be created with gateway/method names instead of IDs.
=> CASH-1639 - Update API docs

spec/openapi.yaml, web/swagger-docs/changelog.md
Adds documentation for https://github.com/MyOnlineStore/myonlinestore/pull/7644
- None
- None
- None
=> BIER-2420 update API documentation and changelog

spec/openapi.yaml, web/swagger-docs/changelog.md
- None
- None
- Require options in configurator lists
=> MWW-8449 Require options in configurator lists

.gitignore, Dockerfile.dev, Makefile, docker-compose.dist.yml
- Traefik set-up on port 9080
- None
- None
=> Traefik set-up for Partner API

spec/openapi.yaml, web/swagger-docs/changelog.md
- None
- None
- https://myonlinestore.atlassian.net/browse/BIER-2361
=> BIER-2361 📄 Update API docs to include base64 image upload

spec/openapi.yaml
=> BIER-2828 Update documentation to include the possibility to filter for a specific array of ids

spec/openapi.yaml
=> CASH-84 - Endpoint to retrieve a single customer

spec/openapi.yaml
Includes a small fix for the single customer endpoint
=> CASH-85 - Customer Listing Documentation

spec/openapi.yaml, web/swagger-docs/changelog.md
- None
- None
- Documented `Article`.`uuid`.
=> BIER-3079 Update changelog to include all changes in this story

spec/openapi.yaml
=> CASH-2148 Added region_code field to Store resource

spec/openapi.yaml, web/swagger-docs/changelog.md
=> BIER-3079 Add `uuids` query parameter

spec/openapi.yaml, web/swagger-docs/changelog.md
=> BIER-3091 Update changelog

spec/openapi.yaml, web/swagger-docs/changelog.md
- None
- None
- Added `is_main` to __getCategoryArticles__ endpoint
=> MWW-8740 Update documentation

spec/openapi.yaml, web/swagger-docs/changelog.md
Does just that!
- None
- None
- None
=> BIER-3226 Add `taxable` to documentation and changelog

spec/openapi.yaml
haven't checked these changes functionally because I don't know how to build the documentation of this in our local setup
=> chore(CASH-2500): added partner information to order

spec/openapi.yaml, web/swagger-docs/changelog.md
=> Revert "chore: Add `trial_end_date` to `Store` entity (#60)"

spec/openapi.yaml
=> chore(CASH-2605): added documentation to retrieve transactions per order

spec/openapi.yaml
Tried to make it as consistent as possible with the customer endpoints.
=> feat(CASH-2805): Added documentation for order payment endpoints

spec/openapi.yaml
Documentation that describes the changes made in https://github.com/MyOnlineStore/myonlinestore/pull/9783
=> feat(CASH-3130): Updated documentation for reward discountcodes

spec/openapi.yaml
Adds the remove image endpoint to the docs made in https://github.com/MyOnlineStore/myonlinestore/pull/11475.
=> feat(MOS-1701): Add docs for the remove image endpoint

spec/openapi.yaml
Fixed method of endpoint in docs.
=> fix(MOS-1701): Fix the method of the endpoint
